version: '3'
services:
    app:
        container_name: app
        restart: always
        image: pc-app
        build: .
        ports:
            - '5000:5000'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'
        command: mongod --port 27017 --bind_ip_all
